# Pour lancer le docker
# docker compose up -d --build --remove-orphans --force-recreate <forum>
#-Lance le docker compose dans le document.
#------------------- lance en detach mod, en arrière plan, évite d'immobiliser le terminal mobilisé.
#---------------------- build l'image.
#----------------------------- supprime les dockers qui tournent déjà.
# Attention cela relance tous les services du docker compose présent dans le dossier.

# docker exec -ti <forum> bash
# exécute docker dans le terminal, nous évoluons alors dans le container en lui-même.
services:
  forum:  
    #image: golang:1.22.2 # Seconde manière de faire.
    build: . # va chercher le fichier dockerfile.
    container_name: forum
    restart: unless-stopped
    init: true
    # volumes: 
      # - ./:/app
      # - ./test:/app/test3000
    ports:
      - 8086:8086 # le premier c'est mon pc, le second c'est le container
    networks: 
      - web

# Créé un réseau de containers, où les containers peuvent communiquer.
networks: 
  web: 
    # external: true # /!\ Option à supprimer si le réseau exite déjà. Sinon l'absence de cette option va créer le réseau.