version: '3.8'

services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: forum
      MYSQL_USER: forum_user
      MYSQL_PASSWORD: forum_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  forum-backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: forum_user
      DB_PASSWORD: forum_pass
      DB_NAME: forum

volumes:
  mysql-data:
